### ISSUE TITLE
This Version Did Not Work For Me

### ISSUE THREAD

**Issue by SolStis86** [CWSpear/bootstrap-hover-dropdown#129] opened 2015-09-22 17:07 UTC
Im not sure if theres some deeper issues with bootstrap core js but this version didnt work... The new version you posted did however so Ive used that and it works great...

I added some additional 

$(current).find('.dropdown-menu').fadeIn('fast');

$(current).find('.dropdown-menu').fadeOut('fast');

Within the mouseenter and leave event handlers for fading in and out.. looks and works great so thanks!

**Comment by CWSpear** [comment] 2015-09-22 17:47
I'm not sure what you're talking about? What version didn't work? What version did?

**Comment by SolStis86** [comment] 2015-09-22 17:56
OH sorry it was the revised version posted by redavis!

http://mediaflydesign.com/plugins/bs-hover.revised.js

The one from this repo didnt work at all for some reason....

**Comment by CWSpear** [comment] 2015-09-22 17:57
What do you mean by "didn't work?"

What browser (and version) and OS (and version)?

**Comment by CWSpear** [comment] 2015-09-22 17:58
What version of Bootstrap are you using?

**Comment by SolStis86** [comment] 2015-09-22 17:58
3.3.5 latest

**Comment by CWSpear** [comment] 2015-09-22 18:00
What do you mean by "didn't work?"

What browser (and version) and OS (and version)?

**Comment by SolStis86** [comment] 2015-09-22 18:02
The menu didnt appear on hover basically... i'd added the data-hover attribute as instructed and included the code as instructed.... 

CHrome Version 45.0.2454.93 m
W10

**Comment by SolStis86** [comment] 2015-09-22 18:02
ive emailed you a working example of the code

**Comment by CWSpear** [comment] 2015-09-22 18:02
I'd like to see the version that wasn't working, if possible.

**Comment by SolStis86** [comment] 2015-09-22 18:03
ill swap out the include, bear with

**Comment by SolStis86** [comment] 2015-09-22 18:04
k live

**Comment by CWSpear** [comment] 2015-09-22 18:07
Hmm... strange, it's working for me (it's the same as the other one, but no fade). 

I'm on a Mac (10.10.5), tho, Chrome version 45.0.2454.99.

**Comment by SolStis86** [comment] 2015-09-22 18:08
The demo here: http://cameronspear.com/demos/bootstrap-hover-dropdown/ isnt working on mine either...  odd...

**Comment by SolStis86** [comment] 2015-09-22 18:08
does the fade version work on yours?

**Comment by CWSpear** [comment] 2015-09-22 18:08
Yes

**Comment by SolStis86** [comment] 2015-09-22 18:08
Fk knows... theres no console errors showing at all

**Comment by CWSpear** [comment] 2015-09-22 18:12
I just tried on my PC which is also running Windows 10. It's the same version of Chrome as my Mac (except the `m` at the end). My demo page works there.

Do you have any of that touch-enabled/tablet stuff active?

**Comment by SolStis86** [comment] 2015-09-22 18:14
Yes i think thats the Issue... i just commented out the code for the ontouchenabled check and it worked... I have touchscreen laptop...

**Comment by SolStis86** [comment] 2015-09-22 18:29
Emailed u version with fade func built in

**Comment by CWSpear** [comment] 2015-09-22 19:14
Ok, that officially makes this issue a duplicate of https://github.com/CWSpear/bootstrap-hover-dropdown/issues/68.

**Closed by CWSpear** 2015-09-22 19:14 UTC

**Comment by SolStis86** [comment] 2015-09-22 19:17
sorry lol
